
import os
import subprocess

def run_rtmscore_and_append_result(pocket_file, ligand_file, model_path, output_file, index):
    # Build the RTMScore command
    rtmscore_command = [
        "python", "./RTMScore-main/example/rtmscore.py",
        "-p", pocket_file, "-l", ligand_file,
        "-m", model_path
    ]
    
    # Run the RTMScore command
    result = subprocess.run(rtmscore_command, capture_output=True, text=True)
    if result.returncode == 0:
        # Read and process the out.csv file generated by RTMScore
        with open("out.csv", "r") as temp_file:
            next(temp_file)  
            for line in temp_file:
                with open(output_file, "a") as out_file:
                    out_file.write(f"{index},{line}")
    else:
        with open(output_file, "a") as out_file:
            out_file.write(f"{index},ERROR: {result.stderr}\n")
    print(f"Processed {pocket_file} and {ligand_file} with index {index}")

output_file = "17-2-total.csv"
with open(output_file, "w") as file:
    file.write("Index,Model_Index,RTMScore\n")  

# Define the RTMScore model path
model_path = "./RTMScore-main/trained_models/rtmscore_model1.pth"
workdir = "."  

for index in range(1, 501):
    pocket_file = os.path.join(workdir, f"pro-pocket-{index}.pdb")
    ligand_file = os.path.join(workdir, f"lig-{index}.sdf")

    if os.path.exists(pocket_file) and os.path.exists(ligand_file):
        # If both pocket and ligand files are present, perform RTMScore and process the results
        run_rtmscore_and_append_result(pocket_file, ligand_file, model_path, output_file, index)
    else:
        # If the pocket or ligand file does not exist, record the situation
        with open(output_file, "a") as file:
            file.write(f"{index},MISSING\n")
        print(f"Missing files for index {index}, skipping...")

pocket_files = [f"pro-pocket-{i}.pdb" for i in range(1, 501)]
ligand_files = [f"lig-{i}.sdf" for i in range(1, 501)]

for filename in pocket_files + ligand_files:
    filepath = os.path.join(workdir, filename)
    if os.path.exists(filepath):
        os.remove(filepath)
        print(f"Deleted: {filename}")
    else:
        print(f"Not found: {filename}")

print("Deletion of temporary pocket and ligand files is complete.")